CREATE TABLE IF NOT EXISTS product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ean         VARCHAR(255)                            NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    price       DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id),
    CONSTRAINT unique_ean UNIQUE (ean)
);

CREATE INDEX idx_product_ean ON product (ean);

CREATE TABLE IF NOT EXISTS supplier
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reference VARCHAR(255)                            NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_supplier PRIMARY KEY (id),
    CONSTRAINT unique_reference UNIQUE (reference)
);

CREATE INDEX idx_supplier_reference ON supplier (reference);
